### PR TITLE
Proportional tax

### LINKED ISSUE #27: Proportional Tax
Make the mechanism take a proportional tax from each province rather than a flat tax.

### PR DESCRIPTION
**Pull request by Dan2k03**
Created the proportional tax for our mechanism. This takes a province's percentage of contribution to the total budget and multiplies it by the province's total money to take away from the province. Provinces with higher amounts of money are taxed more than lower amounts.

### CODE REVIEW

**Comment by GeorgeR227** [comment]
Not sure if this is ready for review but this errors on my end.

**Comment by Dan2k03** [comment]
What's the error? It was running okay on my end.

**Comment by GeorgeR227** [comment]
```julia
ERROR: MethodError: objects of type Vector{Float64} are not callable
Use square brackets [] for indexing an Array.
Stacktrace:
 [1] mapreduce_first(f::Vector{Float64}, op::Function, x::Float64)
   @ Base .\reduce.jl:424
 [2] mapreduce(f::Vector{Float64}, op::Function, a::Float64)
   @ Base .\reduce.jl:451
 [3] minimum(f::Vector{Float64}, a::Float64; kw::@Kwargs{})
   @ Base .\reduce.jl:732
 [4] redistribution(country::Vector{Province}, budget::Float64; tax_type::Symbol)
   @ CAP_SMC_Project c:\Users\georger\Documents\GitHub\CAP-SMC-Project\src\mechanism.jl:22        
 [5] top-level scope
   @ c:\Users\georger\Documents\GitHub\CAP-SMC-Project\demos\mech_models.jl:22
```

I think the problem is with how the minimum is written.

**Comment by Dan2k03** [comment]
Nevermind, I think I found the issue, let me make another PR.

**Comment by GeorgeR227** [comment]
You should add some tests in `test/mechanism.jl` to test that this works properly. You can use the function I set up there to do that.

**Review by thewatt-7 — APPROVED** [review]
Everything seems to be working!

**Pull request merged**
